version: '3'
services:
  hyperf-skeleton:
    container_name: hybank-api
    image: hyperf-skeleton
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - "9501:9501"
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false

  mysql:
    container_name: hybank-mysql
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hybank
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
